### ISSUE TITLE
The vcfAllSiteParser.py does not work

### ISSUE THREAD

**Issue by liuqpzafu** [stschiff/msmc-tools#11]
Hi, 
Recently I want to use vcfAllSiteParser.py to make the masked bed and vcf files from an input single-sampled vcf file, and I take the following command line as input:

./vcfAllSiteParser.py single-sampled.vcf test.bed > test.vcf

However, I found it keeps running and no any information was printed on the screen, and also output nothing in the test.bed and test.vcf files, even after running for a long time.

So, would you please let me know how to handle this issue? Thanks!

Btw, I attached a small example of my tested vcf file. Please help me to check whether there is something wrong with my input vcf?

Qingpo

####################
##fileformat=VCFv4.1
##contig=<ID=Chr10,length=16910673>
##contig=<ID=Chr9,length=17607432>
##contig=<ID=Chr12,length=19154523>
##contig=<ID=Chr8,length=20292731>
##contig=<ID=Chr11,length=20796451>
##contig=<ID=Chr7,length=21799424>
##contig=<ID=Chr5,length=23192814>
##contig=<ID=Chr6,length=24174485>
##contig=<ID=Chr4,length=26299011>
##contig=<ID=Chr2,length=29142869>
##contig=<ID=Chr1,length=32613412>
##contig=<ID=Chr3,length=33053699>
##reference=file:///dfs1/bio/qingpol/angsd/temperate/africe/../Oglaberrima.fa
##source=SelectVariants
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	IRIS_313-10327
Chr10	291	.	T	G	158.68	PASS	.	GT:AD:DP:GQ:PL	./.:.:.:.:.
Chr10	726	.	C	T	75.08	PASS	.	GT:AD:DP:GQ:PL	1/1:0,3:3:9:72,9,0
Chr10	733	.	G	T	73.94	PASS	.	GT:AD:DP:GQ:PL	1/1:0,3:3:9:73,9,0
Chr10	753	.	T	C	299.23	PASS	.	GT:AD:DP:GQ:PL	1/1:0,1:1:3:22,3,0
Chr10	772	.	T	A	1234.59	PASS	.	GT:AD:DP:GQ:PL	./.:.:.:.:.
Chr10	784	.	C	G	724.7	PASS	.	GT:AD:DP:GQ:PL	0/0:1,0:1:3:0,3,22
Chr10	1025	.	A	C	50.77	PASS	.	GT:AD:DP:GQ:PL	0/0:1,0:1:3:0,3,27
Chr10	1036	.	C	T	102.09	PASS	.	GT:AD:DP:GQ:PL	0/0:1,0:1:3:0,3,25
Chr10	3804	.	A	G	715.7	PASS	.	GT:AD:DP:GQ:PL	1/1:0,1:1:3:27,3,0
Chr10	3807	.	C	T	70.64	PASS	.	GT:AD:DP:GQ:PL	0/0:1,0:1:3:0,3,26
Chr10	3862	.	C	T	536.78	PASS	.	GT:AD:DP:GQ:PL	./.:.:.:.:.
Chr10	3884	.	T	C	726.3	PASS	.	GT:AD:DP:GQ:PL	./.:.:.:.:.
Chr10	3973	.	A	G	395.26	PASS	.	GT:AD:DP:GQ:PL	./.:.:.:.:.
Chr10	4150	.	C	T	634.72	PASS	.	GT:AD:DP:GQ:PL	0/0:2,0:2:3:0,3,28

####################

**Comment by YossGG** [comment]
Hello  liuqpzafu,
I'm having the same error. 
I'm wondering if did you get to fix the problem?
I hope you may help me


Best wishes,

Yocelyn

**Comment by JesseGarcia562** [comment]
Hi, 

In order to use the vcfAllSiteParser.py script I ran something like this using python 2.7: 

cat input_chr3.vcf | python vcfAllSiteParser.py chr3 chr3Mask_output_bed.gz > chr3_output.vcf

If you look at the script you can see it reads in data from the "sys.stdin." That means it's expecting your input from the standard in. That is what **cat input_chr3.vcf** does. It puts input_chr3.vcf in your stdin. 

The **"I"** pipes your stdin to the script **vcfAllSiteParser.py** and lets the script read it. It is not a capital "i". 

The **chr3** tells the script what chromosome you want to be in the first column of your bed file. 

The  **chr3Mask_output_bed.gz** lets you  designate where you want your gzipped bed file to be written. To read this file after it's created you will need a command like **zcat**. 

The **chr3_output.vcf** lets you designate where you want your output vcf to be.

**Comment by mano1988** [comment]
Hi,

Does vcfAllSiteParser.py works for consensus call only? Can we use it for variant only vcf files.

Thanks

**Comment by stschiff** [comment]
Depends all on what you want to do... Look, it's a 5 year old script, I haven't maintained it, it's _extremely_ simple and please just take it as piece of code to modify for your own needs.
