### ISSUE TITLE
Problem loading page for mappability masks

### ISSUE THREAD

**Issue by mmaalvarez** [stschiff/msmc-tools#23]
Hi there, the link in this paragraph doesn't work:

_In addition to the mask- and vcf file for each individual, you should use one additional mask per chromosome, the mappability mask, which gives all regions on the chromosome, on which short sequencing reads can be uniquely mapped. For humans (GRCh37), you can download these masks **[here](https://oc.gnz.mpg.de/owncloud/index.php/s/RNQAkHcNiXZz2fd)**._

Could you please provide al alternative source?

Thanks, regards

**Comment by stschiff** [comment]
Strange… for me the link works. Try this:

https://oc.gnz.mpg.de/owncloud/index.php/s/RNQAkHcNiXZz2fd <https://oc.gnz.mpg.de/owncloud/index.php/s/RNQAkHcNiXZz2fd>

Best,
Stephan

**Comment by mmaalvarez** [comment]
Thank you, actually the first link works, the problem was my web browser (I am using Firefox). Using the Microsoft Internet Explorer I can access the files without any problem.

Thanks,

Miguel

**Comment by QianXiaobo** [comment]
Hi Stschiff,
I cannot link to https://oc.gnz.mpg.de/owncloud/index.php/s/RNQAkHcNiXZz2fd any more, does it disabled? I am not sure whether I am in China so that I cannot connect it. I am new in this field, if the size of mappability mask file is not large, could you send it to me (qianxiaobo@genomics.cn) please? or any where you can upload and tell me the website.
Thanks for your gentle.

Best wishes,
Xiaobo Qian

**Comment by stschiff** [comment]
I've updated the package to point to the correct location.
