### ISSUE TITLE
bamCaller.py problem

### ISSUE THREAD

**Issue by llq0325** [stschiff/msmc-tools#9]
Dear All,

I got some error when using the bamCaller.py, here is the log

Traceback (most recent call last):
  File "./bamCaller.py", line 38, in <module>
    mask = utils.MaskGenerator(args.mask, chr_)
AttributeError: module 'utils' has no attribute 'MaskGenerator'

Could you help me figure it out?
Thanks a lot,

Best, 
Langqing

**Comment by stschiff** [comment]
No idea what’s going on there. If utils.py is in the same directory as bamCaller it should just load it correctly.
Stephan

**Comment by houzhe1991** [comment]
Dear All,

I got some error when using the bamCaller.py, here is the log

Traceback (most recent call last):
File "./bamCaller.py", line 38, in 
mask = utils.MaskGenerator(args.mask, chr_)
AttributeError: module 'utils' has no attribute 'MaskGenerator'

Could you help me figure it out?
Thanks a lot,

Best,
Langqing

**Comment by stschiff** [comment]
can't reproduce.

**Comment by martinbagic** [comment]
I got the same error when I was following the [guide ](https://github.com/stschiff/msmc-tools/blob/master/msmc-tutorial/guide.md#prerequisites) because I copied the four scripts (`cgCaller.py`, `generate_multihetsep.py`, `combineCrossCoal.py`, `convert_msmc_to_demes.py`) into /usr/local/bin without copying the utils.py, so it was not available. To resolve the error, `utils.py` also has to be on the path (do not install utils from pip).
